### ISSUE TITLE
Hide Lava Beasts

### ISSUE THREAD

**Issue by Z7-z** [rtaylor4444/UltimateVolcanicMine#10]
Option to hide lava beasts would be great since everyone automatically prays at the start of each round and seeing them is irrelevant and just gets in the way of the beautiful scenery of the mine

**Comment by notheowner** [comment]
Built-in Runelite Menu Entry Swapper has the option to swap the left click option to Walk here or just hide attack options when you are VMing if that's a problem for you. 
Also built-in "Entity Hider" can hide the lava beasts for the "Beautiful scenery of the mine"

**Comment by Z7-z** [comment]
ill just use better npc highlight to hide them, thanks
