### ISSUE TITLE
Notification around 2:05 (or a custom time) to throw water again at final boulder

### ISSUE THREAD

**Issue by Z7-z** [rtaylor4444/UltimateVolcanicMine#11]
Since alot of other notifications are available, it would be very nice if we could get another notification around the 2 minute mark to place the second water at boulder 5. An even more customisable option of setting any notification you desire at any given time within the mine would be even better!

**Comment by notheowner** [comment]
I don't see why this would be needed. There is already a notifier that will alert you when the platform underneath is about to despawn, giving you approximately 5 seconds to move your character away from that tile.
![image](https://user-images.githubusercontent.com/86596679/231953721-b9a65798-9341-4757-8c41-fc80baf53093.png)
